---
Style/MultipleComparison:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/MethodMissing:
  Enabled: false
MultilineBlockChain:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Lint/UselessAssignment:
  Exclude:
  - "**/spec/**/*"
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Style/MixinGrouping:
  Exclude:
  - "**/spec/**/*"
Lint/HandleExceptions:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/WordArray:
  MinSize: 19
Style/SignalException:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/AndOr:
  Enabled: false
Metrics/ClassLength:
  Max: 320
Metrics/LineLength:
  Max: 370
Metrics/ParameterLists:
  Max: 17
Metrics/PerceivedComplexity:
  Max: 18
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Exclude:
  - "**/spec/**/*"
Naming/PredicateName:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/SpaceAroundOperators:
  Exclude:
  - "**/spec/actions_specs/xcodebuild_spec.rb"
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1
  Include:
  - "*/lib/assets/*Template"
  - "*/lib/assets/*TemplateAndroid"
  Exclude:
  - "**/lib/assets/custom_action_template.rb"
  - "./vendor/**/*"
  - "**/lib/assets/DefaultFastfileTemplate"
Naming/FileName:
  Exclude:
  - "**/Dangerfile"
  - "**/Brewfile"
  - "**/Gemfile"
  - "**/Podfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/Deliverfile"
  - "**/Snapfile"
  - "**/*.gemspec"
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
  - require
  - require_relative
  - gem
  - program
  - command
  - raise
  - attr_accessor
  - attr_reader
  - desc
  - lane
  - private_lane
  - platform
  - to
  - describe
  - it
  - be
  - context
  - before
  - after
  - to_not

Style/DefWithParentheses:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
