lane :test do
  version_icon(
    appiconset_path: './spec/fixtures/Valid.appiconset',
    text: "It\nis\nworking"
  )

  UI.success('Check out "./specs/fixtures/Valid-Versioned.appiconset" for the versioned icons')
end
